In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cpu


In [2]:
#tensors

#Creating Tensors

In [3]:
#scalar Tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensoor back as Python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors


Why Random Tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust thsoe random numbers to better represent the data.

`Start with random numbers => look at data => update random numbers => look at data => update random numbers`

In [17]:
#Create random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4)

In [18]:
random_tensor

tensor([[0.3133, 0.6674, 0.4239, 0.4189],
        [0.0257, 0.1371, 0.6296, 0.6346],
        [0.1649, 0.6385, 0.2977, 0.6503]])

In [19]:
random_tensor.ndim

2

In [20]:
#Create a random tensor w/ similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
random_tensor_2 = torch.rand(2,5,5)

In [22]:
random_tensor_2

tensor([[[0.7610, 0.8768, 0.5118, 0.7189, 0.3388],
         [0.8093, 0.1518, 0.9369, 0.2323, 0.9509],
         [0.7312, 0.9387, 0.1074, 0.1541, 0.8339],
         [0.0415, 0.9767, 0.6222, 0.5555, 0.5850],
         [0.8871, 0.6290, 0.8285, 0.7937, 0.4517]],

        [[0.7058, 0.4395, 0.8397, 0.9192, 0.0160],
         [0.7489, 0.2630, 0.3331, 0.6858, 0.6691],
         [0.6972, 0.5103, 0.2354, 0.0627, 0.9258],
         [0.5201, 0.8709, 0.5080, 0.1109, 0.4987],
         [0.0639, 0.1709, 0.1543, 0.1614, 0.9202]]])

# Zeros and Ones

In [23]:
#make tensor of all zeros
zeros = torch.zeros(3,4)

In [24]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
#Create a tensor of all ones
ones = torch.ones(3,4)

In [27]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

## creating a range of tensors and tensors-like

In [29]:
#Use torch.range()
one_to_ten = torch.arange(start = 1, end= 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes
One of the 3 big issues w/ PyTorch and deep learning (errors you will encounter)
1. Tensors not right datatype
2. tensors not right shape
3. Tensors not on right devivce

In [31]:
#Float 32
float_32_tensor = torch.tensor([3, 6, 9], 
                              dtype=torch.float32,# What datatype is the tensor (float32, float16, etc)
                              device = None, # What device is your tensor on
                              requires_grad = False) # Whether or not to track gradients with this tensor's operations

float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [34]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors
## Tensor attributes

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`

In [38]:
# Make a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3991, 0.4221, 0.7465, 0.2404],
        [0.0791, 0.2321, 0.3194, 0.0360],
        [0.3254, 0.7842, 0.5916, 0.1160]])

In [39]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3991, 0.4221, 0.7465, 0.2404],
        [0.0791, 0.2321, 0.3194, 0.0360],
        [0.3254, 0.7842, 0.5916, 0.1160]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Manipulating Tensors
Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [40]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [43]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)


There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:

Inner dimensiosn are the ones closer to the @ sign

* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)`

2. The resulting matrix has the shape of the **outer dimensions**:
- `(2, 3) @ (3, 2)` -> `(2, 2)`
- `(3, 2) @ (2, 3)` -> `(3, 3)`

In [45]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [46]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [47]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

 ## One of the msot commmon errors in deep learning: shape errors

In [48]:
# Shapes for matrix multiplication
tensor_a = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_b = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.matmul(tensor_a * tensor_b)

TypeError: matmul() missing 1 required positional arguments: "other"

In [ ]:
 tensor_a.shape, tensor_b.shape

To fix our shape issues, we can maniuplate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_b.T

In [ ]:
tensor_b

In [ ]:
 #THe matrix multiplication operation works when tensor_b is transposed
print(f"Original shapes: tensor_a = {tensor_a.shape}, tensor_b = {tensor_b.shape}\n")
print(f"New shapes: tensor_a = {tensor_a.shape} (same as above), tensor_b.T = {tensor_b.T.shape}\n")
print(f"Multiplying: {tensor_a.shape} @ {tensor_b.T.shape} <- inner dimensions must match\n")
print("Output:\n")
output = torch.matmul(tensor_a, tensor_b.T)
print(output)
print(f"\n Output shape: {output.shape}")



## Finding the min, max, mean, sum, etc. (Tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)

In [ ]:
# Find the Min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max()

In [ ]:
# Find the mean

# Wrong DataType error, MUST CHANGE IT
# mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


In [49]:
# Find the sum
torch.sum(x), x.sum()

NameError: name 'x' is not defined

## Finding the positional min and max

In [50]:
x

NameError: name 'x' is not defined

In [51]:
# Find the position in tensor that has minimum value w/ argmin
# -> returns index position of target tensor where min value occurs
x.argmin()

NameError: name 'x' is not defined

In [52]:
x[0]

NameError: name 'x' is not defined

In [53]:
# Find the position in tensor that has max value w/ argmax
x.argmax()

NameError: name 'x' is not defined

In [54]:
x[9]

NameError: name 'x' is not defined

 ## Reshaping, stacking, squeezing, and unsqueezing tensors
 
 - Reshaping - reshapes an input tensor to a defined shape
 - View - Return a view of an input tensor of a certain shape but keep same memory as the original tensor
 - Stacking - combine multiple tensors on top of eachother (vstack) or side by side (hstack)
 - Squeeze - removes all `1` dimensions from a tensor
 - Unsqueeze - adds a `1` dimension to a target tensor
 - Permute - Return a view of the input with dimensions permuted (swapped) in a certain way
 
 Ultimate goal of all of these is to manipulate tensor in some way to change the shape. This is because #1 error in tensors are shape issues

In [55]:
import torch

In [56]:
x = torch.arange(1., 10.)

In [57]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
# Add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape
#Reshapes must be compatible w/ original size

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Changing z changes x (because a view of a tensor shares the same memory as the original input)

In [60]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [61]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [63]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}\n")
print(f"Previous shape: {x_reshaped.shape}\n")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}\n")
print(f"New shape: {x_squeezed.shape}\n")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])



In [64]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension w/ unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [65]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order

x_original = torch.rand(size=(224, 224, 3)) #height, width, color channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #color channels, height, width


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [66]:
x_original[0,0,0] = 78

In [67]:
x_original[0,0,0], x_permuted[0,0,0]

(tensor(78.), tensor(78.))

## Indexing (selecting data from tensors)

Indexing w/ pytorch is similar to indexing with NumPy

In [68]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
#Indexing on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [70]:
# Index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [71]:
# Index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [72]:
# You can also use ":" to select 'all' of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [73]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension

x[:, :, 1]

tensor([[2, 5, 8]])

In [74]:
# Get all values of the 0 dimension but only the 1 index value of 
# 1st and 2nd dimension

x[:, 1, 1]

tensor([5])

In [75]:
# Get index 0 of 0th and 1st dimension and all values of 2nd
#dimension
x[0, 0, :]

tensor([1, 2, 3])

In [76]:
# Index on x to return 9
print(x[0][2][2])
# Index on x to return 3,6,9
print(x[0, : , 2])

tensor(9)
tensor([3, 6, 9])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library

And because of this, PyTorch has functionality to interact with it.

- Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
- PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [77]:
# Numpy array to tensor
import torch 
import numpy as np

In [78]:
array = np.arange(1,8)
tensor = torch.from_numpy(array)
array, tensor
# when converting from numpy to pytroch, 
# pytorch reflects numpy's default datatype of float64 
# unless specified otherwise


(array([1, 2, 3, 4, 5, 6, 7]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [82]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2, 3, 4, 5, 6, 7, 8]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [83]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))